export const mockCapsules = [
  {
    id: '1',
    title: '小幸運',
    artist: '田馥甄',
    youtubeUrl: 'https://www.youtube.com/watch?v=pcF3yMpJZfE',
    hashtag: '#華語流行',
    theme: 'orange',
    longitude: 121.5654,
    latitude: 25.0330,
    createdAt: new Date('2024-01-15'),
    createdBy: 'user1',
    isFavorite: false,
  },
  {
    id: '2',
    title: 'Shape of You',
    artist: 'Ed Sheeran',
    youtubeUrl: 'https://www.youtube.com/watch?v=JGwWNGJdvx8',
    hashtag: '#西洋流行',
    theme: 'blue',
    longitude: 121.5644,
    latitude: 25.0320,
    createdAt: new Date('2024-01-14'),
    createdBy: 'user2',
    isFavorite: true,
  },
  {
    id: '3',
    title: 'Dynamite',
    artist: 'BTS',
    youtubeUrl: 'https://www.youtube.com/watch?v=gdZLi9oWNZg',
    hashtag: '#韓流',
    theme: 'purple',
    longitude: 121.5634,
    latitude: 25.0340,
    createdAt: new Date('2024-01-13'),
    createdBy: 'user3',
    isFavorite: false,
  },
  {
    id: '4',
    title: '說好不哭',
    artist: '周杰倫',
    youtubeUrl: 'https://www.youtube.com/watch?v=6VV3lmgGUzs',
    hashtag: '#華語流行',
    theme: 'orange',
    longitude: 121.5674,
    latitude: 25.0310,
    createdAt: new Date('2024-01-12'),
    createdBy: 'user4',
    isFavorite: true,
  },
  {
    id: '5',
    title: 'Blinding Lights',
    artist: 'The Weeknd',
    youtubeUrl: 'https://www.youtube.com/watch?v=4NRXx6U8ABQ',
    hashtag: '#電子音樂',
    theme: 'green',
    longitude: 121.5684,
    latitude: 25.0350,
    createdAt: new Date('2024-01-11'),
    createdBy: 'user5',
    isFavorite: false,
  },
];

export const mockUsers = [
  {
    id: 'user1',
    username: '音樂愛好者',
    longitude: 121.5664,
    latitude: 25.0335,
    currentSong: {
      title: '告白氣球',
      artist: '周杰倫',
    },
  },
  {
    id: 'user2',
    username: 'MelodyHunter',
    longitude: 121.5624,
    latitude: 25.0325,
    currentSong: {
      title: 'Perfect',
      artist: 'Ed Sheeran',
    },
  },
  {
    id: 'user3',
    username: 'KPop粉絲',
    longitude: 121.5694,
    latitude: 25.0315,
    currentSong: {
      title: 'Butter',
      artist: 'BTS',
    },
  },
];